services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSRGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: 
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data:
